/**
 * The sources of every jyotish rule: the Mantra door (Sanskrit verse, our translation) and
 * the Yantra door (the astronomy or arithmetic behind it).
 *
 * - The Sanskrit is in verses.json, copied verbatim from the e-texts by
 *   scripts/fetch-verses.mjs. Keys are "BPHS 6.12": work, chapter, verse.
 * - TRANSLATIONS are Aletheia's own, made from that Sanskrit. Words in brackets are
 *   supplied for sense.
 * - status: 'canon' (the text is clear, or Nilesh has decided where texts conflict — see
 *   `decided`), 'pending' (the texts leave a choice open or conflict; the default awaits
 *   Nilesh's decision, docs/CANON.md), 'unsourced' (a convention with no verse found in the
 *   texts consulted).
 */
import verses from './verses.json' with { type: 'json' };

export const WORKS = {
  BPHS: { title: 'Bṛhat Pārāśara Horā Śāstra', edition: '97-chapter recension, e-text of sanskritdocuments.org (Ahto Jarve et al.); chapter and verse numbers are that e-text’s', script: 'devanagari' },
  BJ: { title: 'Bṛhajjātaka of Varāhamihira', edition: 'e-text of sanskritdocuments.org', script: 'devanagari' },
  PD: { title: 'Phaladīpikā of Mantreśvara', edition: 'e-text of sanskritdocuments.org', script: 'devanagari' },
  SS: { title: 'Sūrya Siddhānta', edition: 'GRETIL e-text (Michio Yano), IAST', script: 'iast' },
} as const;
export type Work = keyof typeof WORKS;

export const VERSES: Readonly<Record<string, string>> = verses.verses;

export type Status = 'canon' | 'pending' | 'unsourced';

export interface Rule {
  title: string;
  verses: readonly string[];
  /** The astronomy or arithmetic, in plain English. */
  yantra: string;
  status: Status;
  /** For 'pending' and 'unsourced': what is open, and the default chosen meanwhile. */
  open?: string;
  /** For rules where the texts disagree and Nilesh decided: the decision, its date and the authority followed. */
  decided?: string;
}

export const TRANSLATIONS: Readonly<Record<string, string>> = {
  // ---- BPHS 3: the grahas ----
  'BPHS 3.10': 'The grahas, in order, are the Sun, the Moon, Mars, Mercury, Jupiter, Venus, Saturn, Rahu and Ketu.',
  'BPHS 3.11': 'Of them the Sun, Saturn and Mars, the waning Moon, Rahu and Ketu are cruel; the rest are gentle. Mercury joined with a cruel graha is cruel.',
  'BPHS 3.19': 'Mercury and Saturn are neuter, the Moon and Venus female; the rest — the Sun, Mars and Jupiter — are to be known as male.',
  'BPHS 3.49': 'Aries, Taurus, Capricorn, Virgo, Cancer, Pisces and Libra are declared the exaltation signs of the Sun and the others in order.',
  'BPHS 3.50': '[Their degrees are] ten, three, twenty-eight, fifteen, five, twenty-seven and twenty. The seventh sign from the exaltation is the debilitation, at those same degrees.',
  'BPHS 3.51': 'For the Sun, in Leo the first twenty degrees are its trikoṇa, the rest its own sign. The Moon’s exaltation is in Taurus over three degrees; the remaining degrees are its trikoṇa.',
  'BPHS 3.52': 'For Mars, in Aries the first twelve degrees are trikoṇa, the rest own sign. Mercury’s exaltation is said to be in Virgo, over fifteen degrees;',
  'BPHS 3.53': 'after that five degrees are its trikoṇa, the rest own sign. For Jupiter, in Sagittarius ten degrees are trikoṇa, the rest own sign.',
  'BPHS 3.54': 'For Venus, in Libra fifteen degrees are trikoṇa, the rest own sign. For Saturn, in Aquarius twenty degrees are trikoṇa, the rest own sign.',
  'BPHS 3.55': 'Counted from its trikoṇa, the lords of the 2nd, 4th, 5th, 8th, 9th and 12th, and the lord of its exaltation, are friends; the others are enemies; those that bear both marks are neutral.',
  'BPHS 3.56': 'Placed in the 10th, 4th, 11th, 3rd, 2nd or 12th from one another, grahas become friends for the time; placed elsewhere they are enemies.',
  'BPHS 3.57': 'A friend both for the time and by nature is a great friend. A friend for the time and neutral by nature is a friend; an enemy for the time and neutral by nature, an enemy;',
  'BPHS 3.58': 'a friend one way and an enemy the other, neutral; an enemy both ways, a great enemy. Having weighed this, the astrologer should state the results of the nativity.',
  'BPHS 3.66': 'Now Gulika and the others are described, from Sunday to Saturday. Divide the daytime into eight and count the parts in order from the lord of the weekday.',
  'BPHS 3.67': 'The eighth part is lordless; Saturn’s part is known as Gulika. Divide the night too into eight and count from the fifth from the weekday lord:',
  'BPHS 3.68': 'the eighth part is called lordless. Saturn’s part is called Gulika; the Sun’s part is called Kāla;',
  'BPHS 3.69': 'Mars’ part is called Mṛtyu, Jupiter’s Yamaghaṇṭaka, Mercury’s Ardhaprahara — each reckoned exactly for one’s own place.',

  // ---- BPHS 6: the sixteen vargas ----
  'BPHS 6.2': 'I shall tell you the sixteen vargas that Brahmā, grandsire of the worlds, declared. Listen, Maitreya.',
  'BPHS 6.3': 'Kṣetra, horā, drekkāṇa, the fourth part, the seventh part, the ninth part, the tenth part, the twelfth part, the sixteenth part,',
  'BPHS 6.4': 'the twentieth part, the twenty-fourth part, the twenty-seventh part, then the thirtieth part, the fortieth part, the forty-fifth part, and after that the sixtieth part.',
  'BPHS 6.5': 'A graha’s kṣetra is the sign it is in, belonging to that sign’s lord. [The horās are] the Sun’s and the Moon’s in an odd sign; in an even sign the reverse.',
  'BPHS 6.6': 'The Pitṛs are the deities of the Moon’s horās, the Devas of the Sun’s. A horā is half a sign; there are twenty-four. Counted from Aries, these horās make two rounds.',
  'BPHS 6.7': 'A drekkāṇa is a third of a sign; there are said to be thirty-six. Counted from Aries, they make three rounds.',
  'BPHS 6.8': 'They belong in order to the sign itself, its fifth and its ninth. Nārada, Agasti and Durvāsā are the deities of the drekkāṇas in movable, [fixed and dual] signs.',
  'BPHS 6.9': 'The lords of the fourth parts are the lords of the kendras counted from the sign itself, from Aries on. [Their deities are] Sanaka, Sananda, Kumāra and Sanātana.',
  'BPHS 6.10': 'In an odd sign the seventh parts are counted from the sign’s own lord; in an even sign, from the lord of its seventh sign.',
  'BPHS 6.11': '[Their deities are] Kṣāra, Kṣīra, Dadhi, Ājya, Ikṣurasa, Madya and Śuddhajala in an odd sign; in an even sign, from Śuddhajala on.',
  'BPHS 6.12': 'The navāṃśas run from the sign itself in a movable sign, from its ninth in a fixed sign, and from its fifth in a dual sign; so the wise should reckon. Deva, Nara and Rākṣasa [are their deities] in movable and the other signs.',
  'BPHS 6.13': 'The tenth parts run from the sign itself in an odd sign and from its ninth in an even sign. The ten guardians of the directions from the east — Indra, Agni, Yama, Rākṣasa,',
  'BPHS 6.14': 'Varuṇa, Māruta, Kubera, Īśāna, Brahmā and Ananta — are their deities in order in an odd sign, in reverse in an even sign.',
  'BPHS 6.15': 'The twelfth parts are counted from the sign itself. Their lords in order are Gaṇeśa, the Aśvins, Yama and Ahi.',
  'BPHS 6.16': 'The sixteenth parts are to be known from Aries, Leo and Sagittarius in movable, [fixed and dual] signs. [Their deities,] Brahmā, Viṣṇu, Hara and Sūrya in an odd sign, in reverse in an even one.',
  'BPHS 6.17': 'Now the lords of the twentieth parts, as Brahmā declared: from Aries in a movable sign, from Sagittarius in a fixed sign, from Leo in a dual sign.',
  'BPHS 6.22': 'The lords of the siddhāṃśas (twenty-fourth parts) run from Leo when the graha is in an odd sign and from Cancer when it is in an even sign. [Their deities are] Skanda, Paraśudhara, Anala,',
  'BPHS 6.26': 'then Ajapād, Ahirbudhnya and Pūṣā. The lords of the bhāṃśas (twenty-seventh parts) are the deities of the nakṣatras, counted from Aries on through the movable signs.',
  'BPHS 6.27': 'The lords of the thirtieth parts in an odd sign are Mars, Saturn, Jupiter, Mercury and Venus, over five, five, eight, seven and five degrees; in an even sign, in reverse.',
  'BPHS 6.28': 'Agni, Samīra, Śakra, Dhanada and Jalada are their deities in order in odd signs; in even signs, the reverse.',
  'BPHS 6.29': 'The lords of the fortieth parts run from Aries in an odd sign and from Libra in an even sign, with their own lords.',
  'BPHS 6.31': 'Likewise the lords of the forty-fifth parts: from Aries in a movable sign, from Leo in a fixed sign, from Sagittarius in a dual sign. Brahmā, Śiva and Viṣṇu in a movable sign;',
  'BPHS 6.33': 'Leave out the signs of the graha’s longitude, double the degrees and the rest, and divide by twelve. The remainder plus one, counted from that same sign, gives the sign whose lord rules the sixtieth part.',

  // ---- BPHS 26: precise aspects ----
  'BPHS 26.3': 'At the 3rd and 10th, the 5th and 9th, the 4th and 8th, and the 7th, they look with a quarter more each time, and give their results so.',
  'BPHS 26.4': 'All look fully at the 7th; Saturn, Jupiter and Mars, moreover, specially at the 3rd and 10th, the 5th and 9th, and the 4th and 8th.',
  'BPHS 26.5': 'That is the general rule taught by earlier teachers. The aspect found from the exact distance is the precise one, as follows.',
  'BPHS 26.6': 'Subtract the aspecting graha from the aspected one. If the distance exceeds six signs, subtract it from ten signs: half of those degrees is the precise aspect.',
  'BPHS 26.7': 'If it exceeds five signs, drop the signs: the degrees doubled are the precise aspect. If it exceeds four signs, take the degrees from five signs: those degrees are the aspect. If it exceeds three signs,',
  'BPHS 26.8': 'take it from four signs and halve, then add thirty: that is the aspect. If it exceeds two signs, drop the signs and add fifteen to the degrees.',
  'BPHS 26.9': 'If it exceeds one sign, drop the sign and halve the degrees: that is the aspect. So for any remainder in signs and degrees. When Saturn is the one aspecting, O twice-born,',
  'BPHS 26.10': 'with one sign or nine signs remaining, the degrees passed or still to go, doubled; with two signs, sixty less half the degrees; with eight signs, the degrees plus thirty.',
  'BPHS 26.11': 'For Mars, with three or seven signs, sixty less the degrees; with two signs, one and a half times the degrees plus fifteen; with six signs, always one rūpa (sixty).',
  'BPHS 26.12': 'For Jupiter, with three or seven signs, half the degrees plus forty-five; with four or eight signs, sixty less twice the degrees.',

  // ---- BPHS 27: strength ----
  'BPHS 27.1': 'Now I shall tell the precise strength arising from position, time and the rest. Subtract the debilitation point from the graha; if more than half the circle, subtract it from the circle;',
  'BPHS 27.2': 'turn it into degrees and divide by three: that is the exaltation strength. In its trikoṇa, own sign, a great friend’s, a friend’s, a neutral’s or an enemy’s sign,',
  'BPHS 27.3': 'and in a great enemy’s sign, the strength of grahas is in order forty-five, thirty, twenty, fifteen, ten, four and two.',
  'BPHS 27.4': 'So too in the horā, drekkāṇa, seventh part, navāṃśa, twelfth part and thirtieth part; their sum is the strength from the seven vargas.',
  'BPHS 27.5': 'Venus and the Moon in an even sign and navāṃśa, the others in an odd one, get a quarter rūpa each. Grahas in kendras and the others get full, half and a quarter in order.',
  'BPHS 27.6': 'Placed in the first, middle and last drekkāṇa, male, neuter and female grahas respectively get a quarter rūpa.',
  'BPHS 27.7': 'From the Sun and Mars subtract the 4th; from Jupiter and Mercury the 7th; from Saturn the lagna; from Venus and the Moon the 10th. If it is more than six signs,',
  'BPHS 27.8': 'subtract it from the circle; the degrees divided by three are the directional strength. The ghaṭīs of the given time from midnight are the nata; thirty less that is [also] called nata.',
  'BPHS 27.9': 'For the Moon, Mars and Saturn the nata doubled, in virūpas; for the others, sixty less that; Mercury always has one rūpa.',
  'BPHS 27.10': 'Now I tell the strength of the lunar half. Subtract the Sun from the Moon; if more than six signs, subtract it from twelve signs; turn it into degrees and divide by three.',
  'BPHS 27.11': 'That is the pakṣa strength of the Moon, Mercury, Venus and Jupiter; subtracted from sixty, it is the pakṣa strength of the cruel grahas.',
  'BPHS 27.12': 'In the three thirds of the day, Mercury, the Sun and Saturn; in the three thirds of the night, the Moon, Venus and Mars, have full strength; Jupiter always.',
  'BPHS 27.13': 'The lords of the year, month and day have fifteen, thirty and forty-five; the lord of the horā sixty. The natural strength was told before:',
  'BPHS 27.14': 'sixty divided by seven, multiplied by one, two and so on, for Saturn, Mars, Mercury, Jupiter, Venus, the Moon and the Sun in order, O twice-born.',
  'BPHS 27.15': 'The khaṇḍas are forty-five, thirty-three and twelve degrees in order. [Take] the sum of the khaṇḍas for the signs of the bhuja of the sāyana graha,',
  'BPHS 27.16': 'plus the next khaṇḍa multiplied by the remaining degrees and divided by thirty, in degrees. [It is] plus or minus in the signs from Libra and from Aries for Saturn and the Moon, by threes of signs;',
  'BPHS 27.17': 'reversed for Mars, the Sun, Jupiter and Venus; for Mercury always plus. Those degrees divided by three are the strength from the course (ayana).',
  'BPHS 27.18': 'As much as the Sun’s ayana strength, so much is its ceṣṭā strength; as much as the Moon’s pakṣa strength, so much is its ceṣṭā strength.',
  'BPHS 27.19': 'Less a quarter of the aspects of cruel grahas, plus a quarter of the aspects of gentle ones; the total, with the aspects of Mercury and Jupiter added: so is a graha’s strength.',
  'BPHS 27.20': 'Now, when two star-grahas are at war with each other, the difference of their strengths is added to the victor’s and taken from the vanquished’s strength.',
  'BPHS 27.21': 'Vakrā, anuvakrā, vikalā, mandā, mandatarā, samā, carā and aticarā: these are the eight motions of the grahas.',
  'BPHS 27.22': 'In retrograde motion the strength is sixty; in anuvakra motion half of that; in vikala motion a quarter; and in mean motion half;',
  'BPHS 27.23': 'in slow motion a quarter; in slower motion half; in fast motion three quarters; and for the very fast, half.',
  'BPHS 27.24': 'Half the sum of the mean and true [longitudes], subtracted from the graha’s own śīghrocca — if more than six signs, taken from the circle — is the ceṣṭā kendra, from Mars on.',
  'BPHS 27.25': 'Turned into degrees and divided by three, it is the ceṣṭā strength. So strength is sixfold: from position, direction, time, aspect, motion and nature.',
  'BPHS 27.32': 'Thirty-nine, thirty-six, thirty, forty-two, thirty-nine, thirty-three and thirty, each multiplied by ten, in order:',
  'BPHS 27.33': 'if the total strength of the Sun and the others [reaches these], they are held to be strong; if more, the strength is full, O twice-born.',

  // ---- BPHS 29–33: pada, upapada, argalā, kārakas ----
  'BPHS 29.2': 'Count from the lagna to the sign the lagna’s lord occupies; as many signs again from there is the sign called the pada of the lagna.',
  'BPHS 29.3': 'The pada of every house is found the same way. The wise call the pada of the first house the chief pada.',
  'BPHS 29.4': 'The house itself or its seventh cannot be the pada. When it falls there, the tenth or the fourth respectively is the pada.',
  'BPHS 29.5': 'Thus, when the lord is in the fourth, the fourth itself is the pada; when the lord is in the seventh, the tenth is the pada.',
  'BPHS 29.6': 'As many signs as a graha’s house lies from the graha, so many signs onward from it is called the graha’s ārūḍha.',
  'BPHS 29.7': 'For a sign with two lords, or a graha with two signs, reckon in the same way up to the stronger; having found the pada, state its results.',
  'BPHS 30.2': 'The pada of the first house is called the chief pada. That of the one which attends on the first house is called upārūḍha;',
  'BPHS 30.3': 'it is named upapada, and also the secondary pada. If it is in a gentle graha’s sign, joined or seen by gentle grahas, …',
  'BPHS 31.3': 'A graha in the 4th, 2nd or 11th makes argalā; grahas in the 10th, 12th and 3rd respectively obstruct it.',
  'BPHS 31.4': 'Obstructors that are weak or fewer in number are not held to obstruct. Where malefics in the 3rd are in excess, Maitreya, though obstructors,',
  'BPHS 31.5': 'there too argalā is to be known, of the reverse kind (viparīta). Even so, the results of grahas and houses are known as held fast by argalā.',
  'BPHS 31.6': 'The 5th too is a place of argalā; the 9th obstructs it. Argalā made by the dark grahas is known by counting in reverse.',
  'BPHS 31.7': 'Argalā from one graha is least, from two middling; from more than two the sages declare it best.',
  'BPHS 31.8': 'Argalā is twofold, from a sign and from a graha. Unobstructed it gives good results; obstructed it is fruitless.',
  'BPHS 32.1': 'Now I shall tell the kārakas, the ātmakāraka and the rest: the seven grahas from the Sun to Saturn, or eight ending with Rahu.',
  'BPHS 32.2': 'If two grahas are equal in degrees, then consider them up to Rahu. So some speak of seven kārakas; some declare eight.',
  'BPHS 32.3': 'Among the Sun and the others, the graha with the most degrees is the ātmakāraka; if the degrees are equal, by more minutes; if those are equal, by more seconds.',
  'BPHS 32.4': '[The first line is corrupt in the e-text; it seems to say the ātmakāraka is not taken by the sign or the whole longitude.] The one with most degrees is the kāraka; the one with fewest is the last kāraka.',
  'BPHS 32.5': 'The one with middle degrees is the middle graha, also called the upagraha. Rahu moves backward, so its degrees are to be subtracted from thirty.',
  'BPHS 32.13': 'Less in degrees than the ātmakāraka is the amātyakāraka; less than that, the bhrātṛ; less than that, the one called mātṛ;',
  'BPHS 32.14': 'less than that, the pitṛ; with fewer degrees still, the putrakāraka; less than the putra, the jñāti; and the one less than the jñāti',
  'BPHS 32.15': 'is to be known as the dārakāraka, without doubt. These are called the movable (cara) kārakas, as the brāhmaṇas declared of old.',
  'BPHS 32.16': 'Others say the mātṛkāraka is the putrakāraka too. If two grahas are equal in degrees at someone’s birth,',
  'BPHS 32.17': 'then the kāraka at the head of them is lost, and good and bad are to be judged from the fixed (sthira) kāraka.',
  'BPHS 33.1': 'Now I shall tell the results of the kārakāṃśa — the ātmakāraka’s own navāṃśa falling in Aries and the other signs — as Brahmā spoke them.',

  // ---- BPHS 46, 47, 51: daśās ----
  'BPHS 46.12': 'Starting from Kṛttikā and going round three times, the daśā lords in order are the Sun, the Moon, Mars, Rahu, Jupiter, Saturn, Mercury, Ketu and Venus.',
  'BPHS 46.13': 'Count from Kṛttikā to the birth nakṣatra and reduce by nine; the remainder gives the daśā lord, and the daśās run on from it.',
  'BPHS 46.14': 'A hundred and twenty years was formerly declared the full life; therefore in the Kali age the viṃśottarī is the chief daśā, O best of the twice-born.',
  'BPHS 46.15': 'Their years in order are six, ten, seven, eighteen, sixteen, nineteen, seventeen, seven and twenty.',
  'BPHS 46.16': 'The years of the daśā multiplied by the part of the nakṣatra passed and divided by its whole extent give the years of the daśā elapsed; subtracted from its measure, what remains.',
  'BPHS 46.155': 'Now I tell the cara daśā of the signs from the lagna to the twelfth. The count from the sign to its lord is known as its daśā.',
  'BPHS 46.156': 'From Aries, groups of three signs are known as padas, odd and even in turn; in an odd pada count forward. In finding the daśā years the count is made in reverse in an even pada.',
  'BPHS 46.157': 'Ketu and Mars are remembered as the two lords of Scorpio; Saturn and Rahu are declared the lords of Aquarius.',
  'BPHS 46.158': 'Now the decision for the signs with two lords. If both lords are together in their own sign,',
  'BPHS 46.159': 'the years are twelve; otherwise reckon by one of them. If one is in its own sign and the other placed elsewhere,',
  'BPHS 46.160': 'take the lord placed elsewhere and reckon the daśā from it. If both are in other signs, then whichever of the two is stronger,',
  'BPHS 46.161': 'from it the daśā is to be taken, forward or backward. In weighing strength here, one with a graha is stronger than one without.',
  'BPHS 46.162': 'If both are with grahas, the one with more grahas is stronger. If equal in grahas, strength is known from the sign:',
  'BPHS 46.163': 'movable, fixed and dual are stronger in that order. If equal in the nature of the sign, the one giving more years is stronger.',
  'BPHS 46.164': 'If one is in its exaltation and the other elsewhere, take the sign of the exalted graha and leave the other.',
  'BPHS 46.165': 'Where an exalted graha is present, add one year; likewise where a debilitated graha is, take away one year.',
  'BPHS 46.166': 'Having considered all this, state the results for the native.',
  'BPHS 46.167': 'Forward or backward according to the pada of the ninth house, beginning from the lagna sign, the wise should reckon the cara daśā.',
  'BPHS 46.195': 'I have already told you the daśā called varṇada. Now the yoginī daśā that Śambhu declared is told.',
  'BPHS 46.196': 'Maṅgalā, Piṅgalā, Dhanyā, Bhrāmarī, Bhadrikā, Ulkā, Siddhā and Saṅkaṭā: these are declared the eight yoginīs.',
  'BPHS 46.197': 'From Maṅgalā the Moon was born, from Piṅgalā the Sun, from Dhanyā the preceptor of the gods (Jupiter), from Bhrāmarī Mars,',
  'BPHS 46.198': 'from Bhadrikā Mercury, from Ulkā Saturn, from Siddhā Venus, and from Saṅkaṭā the dark one (Rahu).',
  'BPHS 46.199': 'Add three to the birth nakṣatra and divide by eight; the remainder, from one, gives the yoginīs from Maṅgalā on.',
  'BPHS 46.200': 'Their daśā years are one, two and so on, rising by one. From the part of the nakṣatra passed and its whole extent, find what has elapsed and what remains.',
  'BPHS 47.35': 'Rahu’s exaltation is Taurus and Ketu’s Scorpio; their mūlatrikoṇas are Gemini and Sagittarius respectively;',
  'BPHS 47.36': 'their own signs are said to be Aquarius and Scorpio — by some, Virgo and Pisces. In their periods there is much happiness and wealth of grain and goods, …',
  'BPHS 51.1': 'The daśā years multiplied by each lord’s own measure and divided by the sum of all the years give the antardaśās severally; so too the pratyantardaśās and the rest.',
  'BPHS 51.2': 'First comes the antardaśā of the daśā lord, the others after it in order; the wise should know the same order in the pratyantara and the rest.',
  'BPHS 51.5': 'Dividing a sign’s daśā by twelve, state the bhuktis of the signs in order; do likewise for the pratyantardaśās and state their results.',

  // ---- BPHS 66–68: aṣṭakavarga ----
  'BPHS 66.15': 'First know the karaṇa and the sthāna, marked by dots and lines; then state the precise results of the aṣṭakavarga in order.',
  'BPHS 66.16': '[For the Sun the karaṇas are] five in the 1st, 2nd, 8th, 3rd and 12th; four in the 7th and the 4th; three in the 6th and 9th; six in the 5th; two in the 10th; and one in the 11th.',
  'BPHS 66.43': 'The others, not named, give sthāna: so the wise know the sthāna. Now I tell the grahas that give sthāna, for the easy understanding of the learned.',
  'BPHS 66.44': '[For the Sun:] in the 2nd, 8th and 1st, Saturn, Mars and the Sun; in the 5th, Jupiter and Mercury; in the 3rd, Mercury, the Moon and the lagna; in the 4th, the lagna, the Sun, Saturn and Mars;',
  'BPHS 66.45': 'in the 10th, those with Mercury and the Moon; in the 11th, all but Venus; in the 12th, the lagna, Venus and Mercury; in the 6th, those with Jupiter and the Moon;',
  'BPHS 66.46': 'in the 7th, the Sun, Mars, Saturn and Venus; in the 9th, the Sun, Mars, Saturn, Mercury and Jupiter. [For the Moon, from the 1st:] Mercury, the Moon and Jupiter; Mars and Jupiter; Mercury, the Sun, the Moon, Mars, Saturn, the lagna and Venus;',
  'BPHS 66.47': 'Jupiter, Venus and Mercury; Mars, Mercury, Venus and Saturn; the Sun, the Moon, Mars, Saturn and the lagna; the Sun, the Moon, Jupiter, Mercury and Venus;',
  'BPHS 66.48': 'the Sun, Mercury and Jupiter; Venus and the Moon; those and those two with the lagna and Mars; all; none: in order, this is the sthāna of the Moon.',
  'BPHS 66.49': '[For Mars:] the lagna, Saturn and Mars; Mars; the lagna, Mercury, the Moon and the Sun; Saturn and Mars; Mercury and the Sun; Mercury, the Moon, Jupiter, the Sun, the lagna and Venus;',
  'BPHS 66.50': 'Saturn and Mars; those two and Venus; Saturn; Mars, the Sun, Jupiter, Saturn and the lagna; all; Jupiter and Venus: so the wise know the sthāna of Mars.',
  'BPHS 66.51': '[For Mercury:] the lagna, Saturn, Mars, Venus and Mercury; the lagna, Mars, the Moon, Venus and Saturn; Venus and Mercury; the lagna, the Moon, Saturn, Venus and Mars; Mercury, the Sun and Venus;',
  'BPHS 66.52': 'Jupiter, Mercury, the Sun, the Moon and the lagna; Mars and Saturn; those two with the lagna, the Moon, Venus [the e-text has Śakra] and Jupiter; Saturn, Mars, the Sun, Mercury and Venus;',
  'BPHS 66.53': 'the lagna, Saturn, Mars, Mercury and the Moon; all; Jupiter, Mercury and the Sun. For Jupiter: in the lagna and the 4th, Jupiter, the lagna, Mars, the Sun [the e-text has akra] and Mercury; in the 2nd,',
  'BPHS 66.54': 'those with the Moon and Venus; in the 3rd, Saturn, Jupiter and the Sun; in the 12th, Saturn; in the 5th, Venus, the Moon, the lagna, Mercury and Saturn; in the 6th, those without the Moon;',
  'BPHS 66.55': 'in the 7th, the lagna, Mars, Jupiter, the Sun and the Moon; in the 8th, Jupiter, the Sun and Mars; in the 9th, Venus, the Sun, the lagna, the Moon and Mercury; in the 11th, all but Saturn;',
  'BPHS 66.56': 'in the 10th, Jupiter, Mercury, Mars, the Sun, Venus and the lagna: so they know it. [For Venus:] the lagna, Venus and the Moon; those; those with Mercury, Saturn and Mars; those without Mercury;',
  'BPHS 66.57': 'in the 5th, the lagna, Mercury, the Moon, Jupiter, Saturn and Venus; Mercury and Mars; none; Venus, the Sun, the Moon, Jupiter, the lagna and Saturn;',
  'BPHS 66.58': 'all but the Sun; in the 10th, Venus, Jupiter and Saturn; all; Mars, the Moon and the Sun: in order, for Venus.',
  'BPHS 66.59': '[For Saturn:] the Sun and the lagna; the Sun; the lagna, the Moon, Mars and Saturn; the lagna and the Sun; Jupiter, Saturn and Mars; in the 6th, all but the Sun;',
  'BPHS 66.60': 'the Sun; the Sun and Mercury; Mercury; the Sun, Mars, the lagna and Mercury; all; then Mars, Mercury, Jupiter and Venus: in order, this the wise know as the sthāna.',
  'BPHS 66.69': 'Karaṇa is to be drawn as a dot, sthāna as a line. Karaṇa is said to give ill, sthāna good results.',
  'BPHS 67.1': 'Having made the aṣṭakavarga of the grahas with the lagna, first do the trikoṇa reduction in all the signs.',
  'BPHS 67.2': 'The trikoṇas are said to be Aries, Leo and Sagittarius; Taurus, Virgo and Capricorn; Gemini, Libra and Aquarius;',
  'BPHS 67.3': 'and Cancer, Scorpio and Pisces, in trine to one another. Write the aṣṭakavarga figures of all the signs one below the other.',
  'BPHS 67.4': 'Whatever is least among a trikoṇa, subtract that much from all three. If one sign of it is empty, do not reduce that trikoṇa.',
  'BPHS 67.5': 'If all signs are equal, the wise should remove all. After that the learned should do the reduction for one lordship.',
  'BPHS 68.1': 'After the trikoṇa reduction, set down the figures of the signs, and then do the reduction for one lordship, each separately.',
  'BPHS 68.2': 'When both signs [of one lord] hold figures, reduce as follows: the other, if without a graha, is made equal to the smaller.',
  'BPHS 68.3': 'If both have grahas, never reduce. If the one with a graha has fewer figures and the one without a graha more,',
  'BPHS 68.4': 'make the one without a graha equal to the smaller. If the one with a graha has more, remove everything in the other.',
  'BPHS 68.5': 'If neither has a graha and they are equal, remove everything. If the one with and the one without a graha are equal, remove everything in the one without.',
  'BPHS 68.6': 'Cancer and Leo are separate signs with separate figures. Having done the reduction for one lordship, then compute the piṇḍa.',

  // ---- Bṛhajjātaka ----
  'BJ 1.4': 'The limbs of Time are the head, face, chest, heart, belly, waist, lower belly, private parts, thighs, knees, shanks and feet. The signs on the circle begin with Aries and Aśvinī, each holding nine nakṣatra quarters; rāśi, kṣetra, gṛha, ṛkṣa, bha and bhavana mean the same.',
  'BJ 1.6': 'Mars, Venus, Mercury, the Moon, the Sun, Mercury, Venus, Mars, Jupiter, Saturn, Saturn and Jupiter are the lords of the signs and of the navāṃśas. The navāṃśas are reckoned from Aries, Capricorn, Libra and Cancer; the lords of the twelfth parts run in order from the sign itself.',
  'BJ 1.7': 'The thirtieth parts of Mars, Saturn, Jupiter, Mercury and Venus are of five, five, eight, seven and five degrees in an odd sign, in reverse in an even sign. The ends of Cancer, Scorpio and Pisces are the junctions of nakṣatra and sign.',
  'BJ 1.11': 'Cruel and gentle, male and female, movable, fixed and dual [are the signs in turn]; Aries, Taurus, Gemini and Cancer with their trines are lords of the east and the other directions. The horās are the Sun’s and the Moon’s in an odd sign, the Moon’s and the Sun’s in an even sign; the drekkāṇas belong to the lords of the sign, its fifth and its ninth.',
  'BJ 1.12': 'Some take the first horā as the sign lord’s and the second as the lord of the eleventh’s; they describe the drekkāṇas too as belonging to the lords of the sign, its twelfth and its eleventh.',
  'BJ 1.13': 'Aries, Taurus, Capricorn, Virgo, Cancer, Pisces and Libra are the exaltations of the Sun and the others, at ten, three, twenty-eight, fifteen, five, twenty-seven and twenty degrees; their sevenths are their debilitations.',
  'BJ 1.14': 'In movable and the other signs, the first, middle and last navāṃśas are vargottama and give good results. Leo, Taurus, Aries, Virgo, Sagittarius, Libra and Aquarius are the trikoṇa signs of the Sun and the others.',
  'BJ 2.15': 'Some hold that the friends of the Sun and the others are, in order: Jupiter; Jupiter and Mercury; Venus and Mercury; all but the Sun; all but Mars; all but the Moon and the Sun; all but the Moon, Mars and the Sun. In Satya’s teaching the friends are the lords of the 2nd, 12th, 5th and 9th from the trikoṇa sign, of the exaltation, of the 8th and of the 4th — by the rule of their marks, and not otherwise, since that would contradict it.',
  'BJ 2.16': 'Saturn and Venus are the Sun’s enemies, Mercury neutral, the rest friends. The Sun and Mercury are the Moon’s friends, the rest neutral. Jupiter, the Moon and the Sun are Mars’ friends, Mercury its enemy, Venus and Saturn neutral. The Sun and Venus are Mercury’s friends, the Moon its enemy, the others neutral.',
  'BJ 2.17': 'Mercury and Venus are Jupiter’s enemies, Saturn neutral, the others friends. Mercury and Saturn are Venus’ friends, Mars and Jupiter neutral, the other two enemies. Venus and Mercury are Saturn’s friends, Jupiter neutral, the others enemies. These I have told by the trikoṇa signs and the rest.',
  'BJ 2.18': 'Placed in each other’s 2nd, 12th, 11th, 3rd, 10th or 4th they are friends for the time — some say in their exaltation too — otherwise enemies. Having reckoned the natural friends, neutrals and enemies, and then the temporal ones, assign great friend and the rest.',
  'BJ 2.20': 'The Sun and the Moon in the northern course, the others when retrograde or meeting [the Moon], and in war those placed to the north with ample rays, are to be reckoned strong in motion (ceṣṭā).',
  'BJ 9.1': 'The Sun is favourable in the 1st, 11th, 4th, 8th, 2nd, 10th, 9th and 7th from itself; the same from Mars and from Saturn; from Venus in the 7th, 12th and 6th; from Jupiter in the 9th, 5th, 11th and 6th; from the Moon in the 10th, 3rd, 11th and 6th; from Mercury in those and the 12th, 9th and 5th; from the lagna in those [10th, 3rd, 11th, 6th] with the 4th and 12th.',
  'BJ 9.2': 'The Moon is favourable from the lagna in the 6th, 3rd, 10th and 11th; from Mars in those with the 2nd, 5th and 9th; from itself in those with the 7th and 1st; from the Sun in those with the 8th and 7th; from Saturn in the 6th, 3rd, 11th and 5th; from Mercury in the 5th, 3rd, 11th, 8th and the kendras; from Jupiter in the 12th, 11th, 8th and the kendras; from Venus in the 9th, 4th, 5th, 3rd, 11th, 10th and 7th.',
  'BJ 9.3': 'Mars is favourable from the Sun in the upacayas (3rd, 6th, 10th, 11th) with the 5th; from the lagna in those with the 1st; from the Moon in those without the 10th; from itself in the kendras, 8th, 11th and 2nd; from Saturn in the 9th, 11th, 8th and the kendras; from Mercury in the 6th, 3rd, 5th and 11th; from Venus in the 6th, 12th, 11th and 8th; from Jupiter in the 10th, 12th, 11th and 6th.',
  'BJ 9.4': 'Mercury is favourable from Venus in the 2nd, 1st, 11th, 8th, 9th and 4th, with the 3rd and 5th; from Saturn and Mars in those [2nd, 1st, 11th, 8th, 9th, 4th] with the 10th and 7th; from Jupiter in the 12th, 6th, 11th and 8th; from the Sun in the 9th, 11th, 6th, 5th and 12th; from itself in those with the 1st, 10th and 3rd; from the Moon in the 6th, 2nd, 11th, 8th, 4th and 10th; from the lagna in those with the 1st.',
  'BJ 9.5': 'Jupiter is favourable from Mars in the 10th, 2nd, 1st, 8th, 7th, 11th and 4th; from itself in those with the 3rd; from the Sun in those with the 3rd and 9th; from Venus in the 5th, 2nd, 9th, 10th, 11th and 6th; from the Moon in the 7th, 11th, 2nd, 9th and 5th; from Saturn in the 3rd, 6th, 5th and 12th; from Mercury in the 10th, 5th, 6th, 2nd, 4th, 11th, 1st and 9th; from the lagna in those with the 7th.',
  'BJ 9.6': 'Venus is favourable from the lagna in the 1st to 5th, 11th, 8th and 9th; from the Moon in those with the 12th; from itself in those with the 10th; from Saturn in the 4th, 3rd, 5th, 9th, 10th, 8th and 11th; from the Sun in the 8th, 11th and 12th; from Jupiter in the 9th, 10th, 11th, 8th and 5th; from Mercury in the 5th, 3rd, 11th, 9th and 6th; from Mars in the 3rd, 9th, 6th, 5th, 11th and 12th.',
  'BJ 9.7': 'Saturn is favourable from itself in the 3rd, 5th, 11th and 6th; from Mars in those with the 10th and 12th; from the Sun in the kendras, 11th, 8th and 2nd; from the lagna in the upacayas with the 1st and 4th; from Mercury in the 9th, 11th, 6th, 10th, 12th and 8th; from the Moon in the 3rd, 6th and 11th; from Venus in the 6th, 11th and 12th; from Jupiter in the 11th, 12th, 5th and 6th.',
  'BJ 9.8': 'So the favourable places are told; the rest are unfavourable. The more of them, the fuller the result they give from the birth sign. The favourable is nourished by grahas in upacayas, friends’ signs and their exaltation; the unfavourable, by those in the other houses, in debilitation and in enemies’ signs.',

  // ---- Phaladīpikā ----
  'PD 4.2': 'The full Moon has ceṣṭā strength, the Sun in its northern course, the retrograde, and in war those placed to the north with bright, abundant rays; exaltation strength in exaltation. Directional strength: the Sun and Mars in the 10th, the Moon and Venus in the 4th, Mercury and Jupiter in the lagna, Saturn in the 7th. Ayana strength: Mercury, Saturn and the Moon in the southern course, the others in the other.',

  // ---- Sūrya Siddhānta ----
  'SS 1.51': 'The civil day-count [from creation] gives, from the Sun, the lords of the day, month and year. Divided by seven, the remainder, counted from the Sun, is the lord of the day.',
  'SS 1.52': 'The day-count divided by the days of a month and of a year, the quotients multiplied by two and by three and increased by one, then divided by seven: the remainders are the lords of the month and the year.',
  'SS 1.55': 'Jupiter’s elapsed revolutions multiplied by twelve, with the signs of the current one added, divided by sixty: [the remainder gives] the years from Vijaya.',
  'SS 2.64': 'The extent of a nakṣatra is 800 minutes, of a tithi 720. A graha’s minutes divided by the nakṣatra extent give the nakṣatras passed; [the remainder] by its daily motion, the days.',
  'SS 2.65': 'The minutes of the sum of the Sun and the Moon divided by the nakṣatra extent give the yogas; the minutes passed and to come, times sixty, divided by the sum of their daily motions, give the nāḍīs.',
  'SS 2.66': 'The minutes of the Moon less the Sun divided by the tithi extent give the tithis; the minutes passed and to come, times sixty, divided by the difference of their daily motions, give the nāḍīs.',
  'SS 2.67': 'The fixed [karaṇas] are Śakuni, Nāga, Catuṣpada the third, and Kiṃstughna, from the latter half of the dark fourteenth.',
  'SS 2.68': 'After them come the seven movable karaṇas, Bava and the rest; in a month each of these karaṇas comes round eight times.',
  'SS 2.69': 'Every karaṇa is reckoned to last half a tithi. So the true motion of the Sun and the other grahas has been told.',
  'SS 7.1': 'Between the star-grahas there are war and meeting; with the Moon, meeting; with the Sun, setting.',
  'SS 7.12': 'Then find the two latitudes anew for that time: in the same direction their difference, in opposite directions their sum, is the distance between the grahas.',
  'SS 7.19': 'When their rays touch each other it is the war called aṃśuvimarda; when less than a degree apart, it is the war called apasavya, if one of them is small.',
  'SS 7.20': 'When more than a degree apart and both strong, it is a meeting. In the apasavya war the vanquished is the one covered, small and without light,',
  'SS 7.21': 'rough, discoloured, struck, standing to the south. The victor is the one to the north, bright and large — or, even in the south, the one that is strong.',
  'SS 7.22': 'If both, though close, are bright, it is a meeting; if both are small and struck, they are kūṭa and vigraha.',
  'SS 7.23': 'Venus, whether north or south, is mostly the victor. The meeting of these with the Moon is to be computed in the same way.',
  'SS 9.2': 'Jupiter, Mars and Saturn, greater [in longitude] than the Sun, set in the west; less, they rise in the east; so too Venus and Mercury when retrograde.',
  'SS 9.3': 'The Moon, Mercury and Venus, being swift, set in the east when less than the Sun and rise in the west when greater.',
  'SS 9.4': 'For setting in the west and rising in the east, take the Sun and the graha at sunset and at sunrise; by day as well; then apply the visibility correction (dṛkkarma) to the graha.',
  'SS 9.5': 'Then the prāṇas between their rising points (lagnas), divided by sixty, are the kālāṃśas; in the west, with six signs added to both, likewise the prāṇas between those points.',
  'SS 9.6': 'Jupiter’s setting arc is eleven degrees, Saturn’s fifteen, Mars’ ten and seven.',
  'SS 9.7': 'Venus sets in the west and rises in the east at eight degrees, being large; it sets in the east and rises in the west at ten, being small.',
  'SS 9.8': 'So Mercury sets and rises at twelve and at fourteen degrees from the Sun, when retrograde and when swift.',
  'SS 9.9': 'With more kāla-degrees than these the grahas are visible in the world; with fewer they are invisible, their forms seized by the Sun’s rays.',
  'SS 10.1': 'The rising and setting of the Moon too are found as before: at twelve degrees it becomes visible in the west and passes out of sight in the east.',
  'SS 12.78': 'Going down from Saturn, every fourth [sphere] is a lord of the day; the lords of the years likewise every third.',
  'SS 12.79': 'Going up from the Moon are the lords of the months; the lords of the horās go down one by one from Saturn.',
  'SS 14.2': 'Of these, four serve in practice: the solar, lunar, sidereal and civil measures. The sixty-year cycle is known by Jupiter’s measure; the others are not in constant use.',
  'SS 14.9': 'From the Sun’s entry into Makara, six months are the northern course; likewise from its entry into Karka, six months are the southern course.',
  'SS 14.10': 'The seasons, Śiśira and the rest, are of two signs each, from there; Meṣa and the others are the twelve months, and they make the year.',
  'SS 14.12': 'The Moon’s daily departure eastward from the Sun gives the lunar measure; a tithi is to be known as twelve degrees.',
  'SS 14.13': 'Tithi, karaṇa, marriage, tonsure and all rites, and vows, fasts and journeys, are taken by the lunar measure.',
  'SS 14.14': 'A lunar month of thirty tithis is a day of the Pitṛs; their night and day divide at the end and the middle of the month.',
  'SS 14.15': 'One turning of the circle of asterisms is a sidereal day. The months are named after the nakṣatras, by the conjunction at the end of the fortnight.',
  'SS 14.16': 'In Kārttika and the others, the conjunction is with two nakṣatras each from Kṛttikā; the last, the one before it, and the fifth, make three months of three.',
};

export const RULES = {
  // ---------- pañcāṅga ----------
  tithi: {
    title: 'Tithi',
    verses: ['SS 2.66', 'SS 14.12'],
    yantra: 'The Moon gains about 12° a day on the Sun. A tithi is each 12° of that gain: tithi n runs while Moon − Sun (sidereal or tropical, the ayanāṃśa cancels) is between 12°(n−1) and 12°n. 1–15 are the bright half, 16–30 the dark half. Start and end are the instants the gain crosses those multiples of 12°, found to 1 ms by root finding on the ephemeris.',
    status: 'canon',
  },
  nakshatra: {
    title: 'Nakṣatra and pada',
    verses: ['SS 2.64', 'BJ 1.4'],
    yantra: 'The sidereal zodiac in 27 equal parts of 800′ (13°20′) from 0° Meṣa; the Moon’s sidereal longitude fixes its nakṣatra, and each nakṣatra has four padas of 3°20′, nine to a sign. Times are the instants the Moon crosses the boundaries.',
    status: 'canon',
  },
  yoga: {
    title: 'Yoga',
    verses: ['SS 2.65'],
    yantra: 'Add the sidereal longitudes of the Sun and the Moon and divide the sum into 27 parts of 800′. Unlike the tithi, the yoga depends on the ayanāṃśa (twice over). The 27 names are the standard list of the pañcāṅgas.',
    status: 'canon',
  },
  karana: {
    title: 'Karaṇa',
    verses: ['SS 2.67', 'SS 2.68', 'SS 2.69', 'SS 14.13'],
    yantra: 'Half a tithi: each 6° of Moon − Sun. Sixty a month: the seven movable karaṇas run eight times from the second half of Śukla Pratipadā (56 halves); the four fixed ones take the last three halves and the first.',
    status: 'canon',
  },
  'karana-fixed-order': {
    title: 'Order of the fixed karaṇas',
    verses: ['SS 2.67'],
    yantra: 'Which name falls on which of the four fixed half-tithis around the new moon: Śakuni on the second half of Kṛṣṇa Caturdaśī, Catuṣpada and Nāga on the two halves of Amāvāsyā, Kiṃstughna on the first half of Śukla Pratipadā.',
    status: 'canon',
    decided: 'Nilesh, 2026-10-03: the pañcāṅga order Śakuni, Catuṣpada, Nāga, Kiṃstughna, as P.V.R. Narasimha Rao (Sanjay Rath’s school) and Drik Panchang give it. SS 2.67 lists Nāga before “Catuṣpada the third”; that order remains as karanaOrder: surya-siddhanta.',
  },
  vara: {
    title: 'Vāra',
    verses: ['SS 1.51', 'BPHS 3.66'],
    yantra: 'The weekday of the local civil date at sunrise; the vāra runs from sunrise to the next sunrise, and its lord is the weekday’s graha (Sunday the Sun, …). The Sūrya Siddhānta counts days from midnight at Laṅkā; the pañcāṅga day, and BPHS 3.66’s day portions, begin at local sunrise.',
    status: 'canon',
  },
  'lunar-month': {
    title: 'Lunar month, adhika and kṣaya',
    verses: ['SS 14.12', 'SS 14.14', 'SS 14.15', 'SS 14.16'],
    yantra: 'An amānta month runs from new moon to new moon. It is named after the sign the Sun enters during it (Caitra holds the Sun’s entry into Meṣa). The Sun moves about 29.1° in a lunation of 29.5 days and the signs are 30° wide, so now and then a month holds no saṅkrānti (adhika, taking the next month’s name) and, rarely, two (kṣaya). Saṅkrāntis are sidereal; the count is exact because the Sun’s sign is taken at the two new moons themselves. Pūrṇimānta months end at the full moon, so their dark half carries the next month’s name.',
    status: 'pending',
    open: 'The texts consulted name months by the full-moon nakṣatra (SS 14.15–16); the saṅkrānti rule for naming and for adhika/kṣaya is Bhāskara II’s (Siddhānta Śiromaṇi), whose verse is not yet transcribed from a primary source. Default: the saṅkrānti rule, the practice of all modern pañcāṅgas.',
  },
  samvatsara: {
    title: 'Saṃvatsara (60-year cycle)',
    verses: ['SS 14.2', 'SS 1.55'],
    yantra: 'Default: the luni-solar cycle of south Indian pañcāṅgas, counted from Śaka years: index = (Śaka year + 11) mod 60 from Prabhava, changing at the start of Caitra. 2026–27 (Śaka 1948) is Parābhava.',
    status: 'pending',
    open: 'SS 14.2 and 1.55 say the cycle is Jupiter’s (bārhaspatya): from Jupiter’s mean revolutions since creation, counted from Vijaya, as north Indian almanacs reckon it. Not implemented; the luni-solar count is the default meanwhile.',
  },
  ritu: {
    title: 'Ṛtu (season)',
    verses: ['SS 14.10'],
    yantra: 'Six seasons of two sidereal signs each, from the Sun’s entry into Makara: Śiśira (Makara, Kumbha), Vasanta (Mīna, Meṣa), Grīṣma, Varṣā, Śarad, Hemanta.',
    status: 'pending',
    open: 'Sidereal signs (literal SS) or the tropical solstices, which today fall about 24° earlier; and some pañcāṅgas name seasons by lunar months instead. Default: sidereal signs.',
  },
  ayana: {
    title: 'Ayana',
    verses: ['SS 14.9'],
    yantra: 'Uttarāyaṇa while the Sun is in the six sidereal signs from Makara to Mithuna, dakṣiṇāyana from Karka to Dhanus. The astronomical solstices are tropical (about 21 December and 21 June); the sidereal Makara saṅkrānti now comes about 24 days later.',
    status: 'pending',
    open: 'Sidereal saṅkrānti (literal SS 14.9, as pañcāṅgas use) or the true solstice. Default: sidereal.',
  },
  'day-eighths': {
    title: 'Gulika kāla and Yamaghaṇṭaka (Yamagaṇḍa)',
    verses: ['BPHS 3.66', 'BPHS 3.67', 'BPHS 3.68', 'BPHS 3.69'],
    yantra: 'Sunrise to sunset is cut into eight equal parts; the first belongs to the weekday’s lord and the next six to the following weekday lords, the eighth to none. The night likewise, starting from the fifth weekday lord. Saturn’s part is Gulika, Jupiter’s Yamaghaṇṭaka.',
    status: 'canon',
  },
  'rahu-kala': {
    title: 'Rāhu kāla',
    verses: [],
    yantra: 'One eighth of the daytime: the 8th on Sunday, 2nd Monday, 7th Tuesday, 5th Wednesday, 6th Thursday, 4th Friday, 3rd Saturday.',
    status: 'unsourced',
    open: 'No verse found in BPHS, Bṛhajjātaka, Phaladīpikā or the Sūrya Siddhānta. Shown as the convention of modern pañcāṅgas until a source is decided.',
  },
  'hora-lords': {
    title: 'Horā lords',
    verses: ['SS 12.78', 'SS 12.79'],
    yantra: 'The grahas in the order of their spheres, slowest first: Saturn, Jupiter, Mars, Sun, Venus, Mercury, Moon. The horā lords follow this order round and round; the first horā of a day belongs to its weekday lord. Because 24 ≡ 3 (mod 7), each day’s lord is the fourth down the order from the previous day’s — the reason for the weekday order.',
    status: 'canon',
  },
  'hora-length': {
    title: 'Length of a horā',
    verses: ['SS 12.79'],
    yantra: 'A horā is a 24th part of the day-and-night.',
    status: 'pending',
    open: 'Equal horās (sunrise to sunrise ÷ 24) or unequal ones (day ÷ 12, night ÷ 12). Default: equal. Switch: hora.',
  },
  muhurta: {
    title: 'Muhūrtas and abhijit',
    verses: [],
    yantra: 'The daytime and the night are each cut into fifteen equal muhūrtas; the eighth muhūrta of the day, centred on local apparent noon, is abhijit.',
    status: 'unsourced',
    open: 'No verse in the texts consulted gives the muhūrtas (they are in the muhūrta works and the Vedic literature). Names not yet shown.',
  },

  // ---------- vargas ----------
  vargas: {
    title: 'The sixteen vargas',
    verses: ['BPHS 6.2', 'BPHS 6.3', 'BPHS 6.4', 'BPHS 6.5', 'BPHS 6.6', 'BPHS 6.7', 'BPHS 6.8', 'BPHS 6.9', 'BPHS 6.10', 'BPHS 6.11', 'BPHS 6.12', 'BPHS 6.13', 'BPHS 6.14', 'BPHS 6.15', 'BPHS 6.16', 'BPHS 6.17', 'BPHS 6.22', 'BPHS 6.26', 'BPHS 6.27', 'BPHS 6.28', 'BPHS 6.29', 'BPHS 6.31', 'BPHS 6.33', 'BJ 1.6', 'BJ 1.11', 'BJ 1.7'],
    yantra: 'Each sign of 30° is cut into n equal parts (D30 into five unequal ones), and the part a graha is in is mapped to a sign by a counting rule. In D9 the parts are the nakṣatra padas (3°20′), so the navāṃśa sign is simply the pada counted from Meṣa, round and round.',
    status: 'canon',
  },
  'varga-hora-drekkana': {
    title: 'D2 and D3 schemes',
    verses: ['BPHS 6.5', 'BPHS 6.6', 'BPHS 6.7', 'BPHS 6.8', 'BJ 1.11', 'BJ 1.12'],
    yantra: 'Parāśara’s horā maps every first or second half of a sign to Siṃha or Karka; the parivṛtti (cyclic) horā runs the 24 halves through the twelve signs twice. Likewise the drekkāṇa.',
    status: 'pending',
    open: 'BPHS 6.6 and 6.7 state both the Sun/Moon horās and the drekkāṇa of the 1st, 5th and 9th, and also that horās and drekkāṇas run from Aries in two and three rounds; BJ 1.12 records yet other views. Default: the Sun/Moon horā and the 1st/5th/9th drekkāṇa. Switches: vargas.hora, vargas.drekkana.',
  },
  'varga-trimshamsha-signs': {
    title: 'D30 signs',
    verses: ['BPHS 6.27', 'BJ 1.7'],
    yantra: 'The thirtieth parts belong to Mars, Saturn, Jupiter, Mercury and Venus; to draw a chart each part needs a sign.',
    status: 'pending',
    open: 'BPHS and BJ give the lords, not the signs. Default: the lord’s odd sign in an odd sign (Meṣa, Kumbha, Dhanus, Mithuna, Tulā) and its even sign in an even sign (Vṛṣabha, Kanyā, Mīna, Makara, Vṛścika).',
  },

  // ---------- states ----------
  dignity: {
    title: 'Exaltation, debilitation, mūlatrikoṇa, own sign',
    verses: ['BPHS 3.49', 'BPHS 3.50', 'BPHS 3.51', 'BPHS 3.52', 'BPHS 3.53', 'BPHS 3.54', 'BJ 1.13', 'BJ 1.14'],
    yantra: 'Fixed places in the sidereal zodiac. Exaltation is a whole sign with a deepest degree; debilitation is the opposite sign at the same degree. Uccha bala measures the arc from the deepest debilitation, 0–180°.',
    status: 'canon',
  },
  'node-dignity': {
    title: 'Dignities of Rahu and Ketu',
    verses: ['BPHS 47.35', 'BPHS 47.36'],
    yantra: 'Whole signs only: the text gives no degrees.',
    status: 'canon',
  },
  friendship: {
    title: 'Natural, temporal and compound friendship',
    verses: ['BPHS 3.55', 'BPHS 3.56', 'BPHS 3.57', 'BPHS 3.58', 'BJ 2.15', 'BJ 2.16', 'BJ 2.17', 'BJ 2.18'],
    yantra: 'Natural friendship is computed, not looked up: from each graha’s mūlatrikoṇa sign, the lords of six houses and of its exaltation sign are friends. The result reproduces Varāhamihira’s table exactly. Temporal friendship depends only on how many signs apart two grahas are in the chart.',
    status: 'canon',
  },
  'benefic-malefic': {
    title: 'Cruel and gentle grahas',
    verses: ['BPHS 3.10', 'BPHS 3.11'],
    yantra: 'Classification used by the aspect strength and argalā. The Moon is cruel through the dark half: Moon − Sun from 180° to 360°. Mercury is cruel when the grahas sharing its sign include more cruel than gentle ones.',
    status: 'canon',
    decided: 'Nilesh, 2026-10-03: following P.V.R. Narasimha Rao (Sanjay Rath’s school), the waxing Moon of Śukla pakṣa is gentle, the waning Moon of Kṛṣṇa pakṣa cruel; Mercury is cruel “when joined by more natural malefics”. BPHS 3.11 gives no threshold. Alternatives kept: waningMoon: under-half-lit (elongation < 90° or > 270°), mercuryCruel: any.',
  },
  combustion: {
    title: 'Combustion (astaṅgata)',
    verses: ['SS 9.2', 'SS 9.3', 'SS 9.4', 'SS 9.5', 'SS 9.6', 'SS 9.7', 'SS 9.8', 'SS 9.9', 'SS 10.1'],
    yantra: 'A graha is lost in the Sun’s rays when it is too close to the Sun to be seen. The arcs: Moon 12°, Mars 17°, Mercury 14° direct / 12° retrograde, Jupiter 11°, Venus 10° direct / 8° retrograde, Saturn 15°, measured as the difference in ecliptic longitude. The Sūrya Siddhānta itself counts kālāṃśas — degrees of sidereal time between the risings or settings at the observer’s latitude, from right ascension and declination: oblique ascension α − arcsin(tan φ tan δ) — kept as the alternative.',
    status: 'canon',
    decided: 'Nilesh, 2026-10-03: the Sūrya Siddhānta arcs are accepted (BPHS, BJ and Phaladīpikā give none), measured in ecliptic longitude, as Visti Larsen (Sanjay Rath’s school) applies them. The literal kālāṃśa measure remains as combustion: kalamsha.',
  },
  'mercury-tie': {
    title: 'Mercury between equal company',
    verses: ['BPHS 3.11'],
    yantra: 'Mercury sharing its sign with as many cruel as gentle grahas.',
    status: 'pending',
    open: 'The majority rule (P.V.R. Narasimha Rao: cruel “when joined by more natural malefics”) does not cover a tie. Default: gentle, since the cruel condition is not met. Listed in `provisional` only for charts where the tie occurs.',
  },
  'graha-yuddha': {
    title: 'Graha yuddha (planetary war)',
    verses: ['SS 7.1', 'SS 7.12', 'SS 7.19', 'SS 7.20', 'SS 7.21', 'SS 7.22', 'SS 7.23', 'BJ 2.20', 'PD 4.2', 'BPHS 27.20'],
    yantra: 'Only the five star-grahas, Mars to Saturn, make war; the Sun “sets” them and the Moon “meets” them. They are at war when less than a degree apart — at the conjunction in longitude the distance is the difference of their latitudes (SS 7.12), so the angular separation on the sky is used. The victor stands to the north: the greater ecliptic latitude.',
    status: 'pending',
    open: 'Separation: true angular distance (SS) or longitude difference (common software). Victor: SS 7.21 also lets a brighter southern graha win, and 7.23 says Venus mostly wins; brightness needs magnitudes, which the engine does not compute. Default: angular distance < 1°, victor = northern graha, with the other clauses reported, not applied.',
  },

  // ---------- strength ----------
  'sphuta-drishti': {
    title: 'Precise aspect (sphuṭa dṛṣṭi)',
    verses: ['BPHS 26.3', 'BPHS 26.4', 'BPHS 26.5', 'BPHS 26.6', 'BPHS 26.7', 'BPHS 26.8', 'BPHS 26.9', 'BPHS 26.10', 'BPHS 26.11', 'BPHS 26.12'],
    yantra: 'Aspect strength in virūpas (0–60) as a piecewise-linear function of the arc from the aspecting to the aspected graha: rising to 60 at 180°, with Saturn, Mars and Jupiter peaking also at their special houses (3rd/10th, 4th/8th, 5th/9th).',
    status: 'canon',
  },
  shadbala: {
    title: 'Ṣaḍbala',
    verses: ['BPHS 3.19', 'BPHS 27.1', 'BPHS 27.2', 'BPHS 27.3', 'BPHS 27.4', 'BPHS 27.5', 'BPHS 27.6', 'BPHS 27.7', 'BPHS 27.8', 'BPHS 27.9', 'BPHS 27.10', 'BPHS 27.11', 'BPHS 27.12', 'BPHS 27.13', 'BPHS 27.14', 'BPHS 27.15', 'BPHS 27.16', 'BPHS 27.17', 'BPHS 27.18', 'BPHS 27.19', 'BPHS 27.20', 'BPHS 27.21', 'BPHS 27.22', 'BPHS 27.23', 'BPHS 27.24', 'BPHS 27.25', 'BPHS 27.32', 'BPHS 27.33'],
    yantra: 'Six kinds of strength in virūpas (60 = 1 rūpa): position (sthāna), direction (dik), time (kāla), motion (ceṣṭā), nature (naisargika) and aspect (dṛk). Each is arithmetic on the chart: arcs from fixed points, which part of the day it is, the Moon’s elongation, declination-like arcs, aspects.',
    status: 'canon',
  },
  'shadbala-saptavarga-mt': {
    title: 'Mūlatrikoṇa in the seven vargas',
    verses: ['BPHS 27.2', 'BPHS 27.3', 'BPHS 27.4'],
    yantra: 'Mūlatrikoṇa is a degree range inside a sign; a divisional chart has signs but no degrees.',
    status: 'pending',
    open: 'BPHS lists mūlatrikoṇa (45) for all seven vargas. Default: mūlatrikoṇa only in D1; in the other vargas a graha in its mūlatrikoṇa sign counts as own sign (30).',
  },
  'dig-bala-points': {
    title: 'Points for directional strength',
    verses: ['BPHS 27.7', 'BPHS 27.8'],
    yantra: 'The 1st, 4th, 7th and 10th are taken as the ascendant, the nadir (MC + 180°), the descendant and the MC, sidereal.',
    status: 'pending',
    open: 'Cusps (ascendant and MC degrees, as in the classical bhāva) or the middle of the whole-sign houses. Default: ascendant and MC.',
  },
  'natonnata-bala': {
    title: 'Day and night strength (nata/unnata)',
    verses: ['BPHS 27.8', 'BPHS 27.9'],
    yantra: 'The distance of the time from midnight, in ghaṭīs (24 minutes), measured by the Sun’s hour angle: 0 at local apparent midnight, 30 at apparent noon. The Moon, Mars and Saturn get twice the distance from noon (60 at midnight); the Sun, Jupiter and Venus twice the distance from midnight (60 at noon); Mercury 60 always.',
    status: 'pending',
    open: 'Midnight as the Sun’s lower transit (apparent solar time; default) or as the middle of the night between sunset and sunrise, or by mean time; and the e-text’s 27.8 is terse.',
  },
  'abda-masa-bala': {
    title: 'Lords of the year and month',
    verses: ['BPHS 27.13', 'SS 1.51', 'SS 1.52'],
    yantra: 'The year lord is the lord of the weekday on which the Sun last entered sidereal Meṣa; the month lord, of the weekday on which it last changed sign (its latest saṅkrānti). The weekday is that of the vāra (sunrise to sunrise) at the birthplace in which the saṅkrānti falls, the saṅkrānti found to the second from the ephemeris. The alternative counts civil days from the Sūrya Siddhānta’s creation epoch (714 402 296 627 days before the Kali epoch, a Friday) and takes the lords of the first days of the current 360- and 30-day periods.',
    status: 'canon',
    decided: 'Nilesh, 2026-10-03: the saṅkrānti method, as in Shri Jyoti Star’s Jaimini edition built on Sanjay Rath’s teaching (“Samkranti lords (Mesha and the last one)”); BPHS 27.13 does not say how to find these lords. The Sūrya Siddhānta day-count (SS 1.51–52) remains as yearMonthLords: surya-siddhanta.',
  },
  'ayana-bala': {
    title: 'Ayana (declination) strength',
    verses: ['BPHS 27.15', 'BPHS 27.16', 'BPHS 27.17'],
    yantra: 'The khaṇḍas 45, 33, 12 add up the sine table of radius 90 at 30°, 60°, 90° (90 sin 30° = 45, 90 sin 60° = 77.9): their sum is 90 × sin of the tropical longitude, a stand-in for declination (sin δ = sin ε sin λ). Strength = (90 ± that) ÷ 3.',
    status: 'pending',
    open: 'The verse gives the khaṇḍa sum and says “plus or minus” without naming 90; taken as 90 ± sum so that strength runs 0–60. The text interpolates linearly between the khaṇḍas (default); alternatives are the exact sine, or the true declination (24° ± δ)/48 × 60 used by many modern books.',
  },
  'cheshta-bala': {
    title: 'Motional strength (ceṣṭā)',
    verses: ['BPHS 27.21', 'BPHS 27.22', 'BPHS 27.23', 'BPHS 27.24', 'BPHS 27.25', 'BPHS 27.18'],
    yantra: 'For Mars to Saturn: the ceṣṭā kendra is the śīghrocca (the mean Sun for Mars, Jupiter, Saturn; the planet’s mean heliocentric longitude for Mercury and Venus) minus the mean of the mean and true geocentric longitudes. Near opposition or inferior conjunction it is near 180° and the strength near 60. Mean longitudes: Meeus, Astronomical Algorithms, Table 31.A (mean equinox of date).',
    status: 'pending',
    open: 'The eight-motion table (27.21–23) has no speed thresholds in the text, so the kendra method (27.24–25) is used. Mean longitudes from modern theory (Meeus) or from the Sūrya Siddhānta’s mean motions.',
  },
  'drik-bala': {
    title: 'Aspect strength (dṛk)',
    verses: ['BPHS 27.19'],
    yantra: 'Sum of the precise aspects received: a quarter of gentle grahas’ aspects added, a quarter of cruel grahas’ taken away.',
    status: 'pending',
    open: 'How to read “with the aspects of Mercury and Jupiter added”: their aspects in full instead of a quarter (default), or in addition. And who is cruel (see benefic-malefic).',
  },
  'yuddha-bala': {
    title: 'War strength',
    verses: ['BPHS 27.20'],
    yantra: 'For two grahas at war, the difference of their strengths moves from the loser to the winner.',
    status: 'pending',
    open: 'Which strengths are compared. Default: the sum of all other components. Depends on graha-yuddha.',
  },

  // ---------- aṣṭakavarga ----------
  ashtakavarga: {
    title: 'Aṣṭakavarga',
    verses: ['BPHS 66.15', 'BPHS 66.16', 'BPHS 66.43', 'BPHS 66.44', 'BPHS 66.45', 'BPHS 66.46', 'BPHS 66.47', 'BPHS 66.48', 'BPHS 66.49', 'BPHS 66.50', 'BPHS 66.51', 'BPHS 66.52', 'BPHS 66.53', 'BPHS 66.54', 'BPHS 66.55', 'BPHS 66.56', 'BPHS 66.57', 'BPHS 66.58', 'BPHS 66.59', 'BPHS 66.60', 'BPHS 66.69', 'BJ 9.1', 'BJ 9.2', 'BJ 9.3', 'BJ 9.4', 'BJ 9.5', 'BJ 9.6', 'BJ 9.7', 'BJ 9.8'],
    yantra: 'For each of the seven grahas, eight donors (the seven and the lagna) each mark certain houses counted from themselves. A sign’s bindus are the number of marks it receives: 0–8. The tables give 48, 49, 39, 54, 56, 52 and 39 marks, 337 in all, whatever the chart.',
    status: 'pending',
    open: 'BPHS 66 (this recension) and BJ 9 differ in four marks with equal totals: in the Moon’s table BPHS has the Moon giving the 9th (BJ: not), Mars not giving the 9th (BJ: gives), Jupiter giving the 2nd instead of the 12th; in Venus’s table Mars gives the 4th instead of the 5th. BPHS states each table twice (by karaṇa and by sthāna) and both agree. Default: BPHS. Switch: ashtakavarga.',
  },
  'trikona-shodhana': {
    title: 'Trikoṇa śodhana',
    verses: ['BPHS 67.1', 'BPHS 67.2', 'BPHS 67.3', 'BPHS 67.4', 'BPHS 67.5'],
    yantra: 'In each triangle of signs (fire, earth, air, water), subtract the smallest count from all three.',
    status: 'canon',
  },
  'ekadhipatya-shodhana': {
    title: 'Ekādhipatya śodhana',
    verses: ['BPHS 68.1', 'BPHS 68.2', 'BPHS 68.3', 'BPHS 68.4', 'BPHS 68.5', 'BPHS 68.6'],
    yantra: 'For the two signs of one lord (all but Karka and Siṃha), reduce by whether each is occupied by a graha, case by case as 68.2–5 list.',
    status: 'pending',
    open: 'Whether Rahu and Ketu count as occupying grahas. Default: the seven grahas only.',
  },

  // ---------- jaimini ----------
  'chara-karaka': {
    title: 'Chara kārakas',
    verses: ['BPHS 32.1', 'BPHS 32.2', 'BPHS 32.3', 'BPHS 32.4', 'BPHS 32.5', 'BPHS 32.13', 'BPHS 32.14', 'BPHS 32.15', 'BPHS 32.16', 'BPHS 32.17'],
    yantra: 'Rank the grahas by their degrees within their signs, the sign itself ignored. Rahu moves backward, so its degrees count from the end of the sign: 30° − degrees. Highest is the ātmakāraka.',
    status: 'canon',
  },
  'karaka-seven': {
    title: 'The seven-kāraka scheme',
    verses: ['BPHS 32.16'],
    yantra: 'With seven kārakas there is one role fewer than with eight: ātma, amātya, bhrātṛ, mātṛ, putra, jñāti, dāra; the father is then seen from the Sun.',
    status: 'canon',
    decided: 'Nilesh, 2026-10-03: drop the pitṛkāraka, as K.N. Rao’s school uses seven (eight remains the default count, CLAUDE.md). BPHS 32.16’s reading, mātṛ = putra with the pitṛkāraka kept, remains as sevenKarakas: matri-putra.',
  },
  arudha: {
    title: 'Ārūḍha padas',
    verses: ['BPHS 29.2', 'BPHS 29.3', 'BPHS 29.4', 'BPHS 29.5', 'BPHS 29.6', 'BPHS 29.7'],
    yantra: 'Reflect the house in its lord: as many signs from the lord as the lord is from the house. If that lands on the house itself, take the 10th from it; if on its 7th, the 4th from the house (29.5 gives the worked example).',
    status: 'canon',
  },
  'two-lords': {
    title: 'Signs with two lords',
    verses: ['BPHS 46.157', 'BPHS 46.158', 'BPHS 46.159', 'BPHS 46.160', 'BPHS 46.161', 'BPHS 46.162', 'BPHS 46.163', 'BPHS 46.164', 'BPHS 29.7'],
    yantra: 'Vṛścika has Mars and Ketu, Kumbha Saturn and Rahu. The stronger is chosen step by step: one in the sign itself defers to the other; then an exalted one; then the one with more grahas; then by its sign (dual > fixed > movable); then the one giving more years.',
    status: 'pending',
    open: 'BPHS gives these tests for the cara daśā (46.158–164) and says only “the stronger” for padas (29.7); the same tests are used for both. Where 46.164 (exaltation) falls in the order is not said; default: before counting grahas.',
  },
  upapada: {
    title: 'Upapada',
    verses: ['BPHS 30.2', 'BPHS 30.3'],
    yantra: 'The ārūḍha of the 12th house.',
    status: 'pending',
    open: '“The one that attends on the first house” is taken by tradition as the 12th (it rises just before the lagna); a literal reading could also give the 2nd. Default: the 12th.',
  },
  karakamsha: {
    title: 'Kārakāṃśa',
    verses: ['BPHS 33.1'],
    yantra: 'The navāṃśa sign of the ātmakāraka.',
    status: 'canon',
  },
  argala: {
    title: 'Argalā',
    verses: ['BPHS 31.3', 'BPHS 31.4', 'BPHS 31.5', 'BPHS 31.6', 'BPHS 31.7', 'BPHS 31.8'],
    yantra: 'Grahas in the 2nd, 4th, 11th and 5th from a sign hold it (argalā); those in the 12th, 10th, 3rd and 9th respectively obstruct. Rahu and Ketu are counted backwards from the sign.',
    status: 'pending',
    open: 'When argalā and obstructors are equal in number, “weaker” obstructors do not obstruct, but no strength measure is named; and how many malefics in the 3rd make viparīta argalā (“in excess”). Default: these cases are reported as undecided, not resolved.',
  },

  // ---------- daśās ----------
  vimshottari: {
    title: 'Viṃśottarī daśā',
    verses: ['BPHS 46.12', 'BPHS 46.13', 'BPHS 46.14', 'BPHS 46.15', 'BPHS 46.16', 'SS 2.64', 'BPHS 51.1', 'BPHS 51.2'],
    yantra: 'Nine lords of 6, 10, 7, 18, 16, 19, 17, 7, 20 years (120 in all), from Kṛttikā thrice round. At birth the Moon’s nakṣatra gives the running lord; the fraction of the nakṣatra the Moon has crossed (arc, since bhabhoga is 800′ of arc, SS 2.64) is the fraction of that daśā already gone. Each period divides into nine in the same order from its own lord, in proportion to the lords’ years, down to five levels.',
    status: 'canon',
  },
  'dasha-year': {
    title: 'Length of a daśā year',
    verses: [],
    yantra: 'Years are converted to days with a fixed year length (default 365.25 days, CLAUDE.md) on the uniform time scale TT.',
    status: 'pending',
    open: 'Already a CLAUDE.md default (365.25), recorded here as the rule the daśā instants depend on; alternatives 360 (sāvana), 365.2422 (tropical), 365.2564 (sidereal).',
  },
  yogini: {
    title: 'Yoginī daśā',
    verses: ['BPHS 46.195', 'BPHS 46.196', 'BPHS 46.197', 'BPHS 46.198', 'BPHS 46.199', 'BPHS 46.200', 'BPHS 51.1', 'BPHS 51.2'],
    yantra: 'Eight yoginīs of 1 to 8 years (36 in all), ruled by the Moon, Sun, Jupiter, Mars, Mercury, Saturn, Venus and Rahu. Birth nakṣatra number + 3, mod 8, gives the first; the balance is the part of the nakṣatra left. Sub-periods divide in proportion, from the period’s own yoginī.',
    status: 'canon',
  },
  'chara-dasha': {
    title: 'Cara daśā',
    verses: ['BPHS 46.155', 'BPHS 46.156', 'BPHS 46.157', 'BPHS 46.158', 'BPHS 46.159', 'BPHS 46.160', 'BPHS 46.161', 'BPHS 46.162', 'BPHS 46.163', 'BPHS 46.164', 'BPHS 46.165', 'BPHS 46.166', 'BPHS 46.167', 'BPHS 51.5'],
    yantra: 'Twelve sign periods from the lagna, forward if the 9th house sign lies in an odd pada (Meṣa–Mithuna, Tulā–Dhanus) and backward otherwise. Each sign’s years = signs counted from it to its lord (forward in an odd pada, backward in an even one), 12 if the lord is in the sign itself; +1 year if the lord is exalted, −1 if debilitated. No balance at birth is given in BPHS.',
    status: 'pending',
    open: 'Sub-periods (51.5, 51.6–11 give conflicting orders) and the second cycle of twelve are not given clearly and are not computed. 46.165 says “where an exalted graha is present” — taken as the sign’s lord (default) rather than any graha in the sign.',
  },
} as const satisfies Record<string, Rule>;

export type RuleId = keyof typeof RULES;
